export enum QueryKey {
  CalculateMonthlyPayroll = "CalculateMonthlyPayroll",
  Company = "Company",
  Companies = "Companies",
  Deparments = "Deparments",
  Jobs = "Jobs",
  Employee = "Employee",
  Employees = "Employees",
  Overtime = "Overtime",
  Payroll = "Payroll",
  Payrolls = "Payrolls",
  Raises = "Raises",
  Users = "Users",
  WorkAbsences = "WorkAbsences",
}
